# values for below can be created with
# echo -n string-to-encode | base64
apiVersion: v1
kind: Secret
metadata:
  name: concourse
type: Opaque
data:
#  concourse-pg-db-url: 
  concourse-url: 
  concourse-tsa-host: 
  concourse-tsa-port: 
  github-auth-client-id: 
  github-auth-client-secret: 
  github-auth-org: 
  github-auth-team: 
#  github-auth-user: 
